server:
  port: 8084
spring:
  application:
    name: payment-service
  datasource:
    url: jdbc:oracle:thin:@localhost:1521:xe
    username: payment_db
    password: sarasu10
    driver-class-name: oracle.jdbc.OracleDriver

    jpa:
      hibernate:
        ddl-auto: update
      show-sql: true
      properties:
        hibernate:
          dialect: org.hibernate.dialect.Oracle12cDialect
          format_sql: true
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
